sonar.projectKey=ganeshp87_market-data-validator
sonar.organization=ganeshp87
sonar.projectName=Market Data Stream Validator
sonar.projectVersion=1.0

# Source paths
sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java,frontend/src

# Java specific
sonar.java.source=21
sonar.java.binaries=backend/target/classes
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

# Frontend specific
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# Exclusions (generated code, config, models)
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,frontend/src/assets/**

# Encoding
sonar.sourceEncoding=UTF-8
