package com.marketdata.validator.store;

import com.marketdata.validator.model.Session;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

import java.time.Instant;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
@ActiveProfiles("test")
class SessionStoreTest {

    @Autowired
    private SessionStore sessionStore;

    @Autowired
    private JdbcTemplate jdbc;

    @BeforeEach
    void setUp() {
        jdbc.update("DELETE FROM ticks");
        jdbc.update("DELETE FROM sessions");
    }

    // --- Create and retrieve ---

    @Test
    void createReturnsSessionWithAutoGeneratedId() {
        Session session = newSession("Test Session", "binance-feed");
        Session created = sessionStore.create(session);

        assertThat(created.getId()).isGreaterThan(0);
    }

    @Test
    void findByIdReturnsCreatedSession() {
        Session session = newSession("BTC Recording", "binance-feed");
        Session created = sessionStore.create(session);

        Optional<Session> found = sessionStore.findById(created.getId());
        assertThat(found).isPresent();
        assertThat(found.get().getName()).isEqualTo("BTC Recording");
        assertThat(found.get().getFeedId()).isEqualTo("binance-feed");
        assertThat(found.get().getStatus()).isEqualTo(Session.Status.RECORDING);
    }

    @Test
    void findByIdReturnsEmptyForMissingId() {
        assertThat(sessionStore.findById(999L)).isEmpty();
    }

    // --- Find all ---

    @Test
    void findAllReturnsOrderedByStartedAtDesc() {
        Instant base = Instant.parse("2026-03-23T10:00:00Z");
        Session s1 = newSessionAt("First", "feed-1", base);
        Session s2 = newSessionAt("Second", "feed-2", base.plusSeconds(60));
        Session s3 = newSessionAt("Third", "feed-3", base.plusSeconds(120));

        sessionStore.create(s1);
        sessionStore.create(s2);
        sessionStore.create(s3);

        List<Session> all = sessionStore.findAll();
        assertThat(all).hasSize(3);
        assertThat(all.get(0).getName()).isEqualTo("Third");
        assertThat(all.get(2).getName()).isEqualTo("First");
    }

    // --- Update status ---

    @Test
    void updateStatusChangesOnlyStatus() {
        Session created = sessionStore.create(newSession("Test", "feed"));

        sessionStore.updateStatus(created.getId(), Session.Status.FAILED);

        Session found = sessionStore.findById(created.getId()).orElseThrow();
        assertThat(found.getStatus()).isEqualTo(Session.Status.FAILED);
        assertThat(found.getName()).isEqualTo("Test");
    }

    // --- Complete ---

    @Test
    void completeSetsStatusAndCounts() {
        Session created = sessionStore.create(newSession("Test", "feed"));

        sessionStore.complete(created.getId(), 500, 1024000);

        Session found = sessionStore.findById(created.getId()).orElseThrow();
        assertThat(found.getStatus()).isEqualTo(Session.Status.COMPLETED);
        assertThat(found.getEndedAt()).isNotNull();
        assertThat(found.getTickCount()).isEqualTo(500);
        assertThat(found.getByteSize()).isEqualTo(1024000);
    }

    // --- Delete ---

    @Test
    void deleteRemovesSession() {
        Session created = sessionStore.create(newSession("Test", "feed"));
        assertThat(sessionStore.findById(created.getId())).isPresent();

        sessionStore.delete(created.getId());
        assertThat(sessionStore.findById(created.getId())).isEmpty();
    }

    @Test
    void deleteDoesNotAffectOtherSessions() {
        Session s1 = sessionStore.create(newSession("Keep", "feed"));
        Session s2 = sessionStore.create(newSession("Remove", "feed"));

        sessionStore.delete(s2.getId());

        assertThat(sessionStore.findById(s1.getId())).isPresent();
        assertThat(sessionStore.findById(s2.getId())).isEmpty();
    }

    // --- Count ---

    @Test
    void countReturnsZeroWhenEmpty() {
        assertThat(sessionStore.count()).isEqualTo(0);
    }

    @Test
    void countReturnsTotalSessions() {
        sessionStore.create(newSession("S1", "feed"));
        sessionStore.create(newSession("S2", "feed"));

        assertThat(sessionStore.count()).isEqualTo(2);
    }

    // --- Timestamps ---

    @Test
    void startedAtPreserved() {
        Instant ts = Instant.parse("2026-03-23T10:00:00.123Z");
        Session session = newSessionAt("Test", "feed", ts);
        Session created = sessionStore.create(session);

        Session found = sessionStore.findById(created.getId()).orElseThrow();
        assertThat(found.getStartedAt()).isEqualTo(ts);
    }

    @Test
    void endedAtNullForRecordingSession() {
        Session created = sessionStore.create(newSession("Test", "feed"));

        Session found = sessionStore.findById(created.getId()).orElseThrow();
        assertThat(found.getEndedAt()).isNull();
    }

    // --- Helpers ---

    private Session newSession(String name, String feedId) {
        return newSessionAt(name, feedId, Instant.now());
    }

    private Session newSessionAt(String name, String feedId, Instant startedAt) {
        Session s = new Session();
        s.setName(name);
        s.setFeedId(feedId);
        s.setStatus(Session.Status.RECORDING);
        s.setStartedAt(startedAt);
        return s;
    }
}
